### ISSUE TITLE
Isan Hanto的二面试题提交仓库

### ISSUE THREAD

**Issue by ljt-qsc** [QSCTech/2021-fall-round-two#10]
###  励精图的二面试题提交仓库

- 链接：https://github.com/ljt-qsc/2021-fall-round-two`

选做题目：to-frontend-newbie

没啥注意事项 小白乱撞

**Comment by dinoallo** [comment]
我已有权限检视您的仓库，感谢您参加求是潮 2021 秋纳二面，先预祝您面试顺利。

Cheers,
仓管 异特龙
