### ISSUE TITLE
李天祎的二面试题提交仓库

### ISSUE THREAD

**Issue by ChangeFWorld** [QSCTech/2021-fall-round-two#12]
链接：https://github.com/Lumine7/2021-fall-round-two
## 选做题目：
1.is-it-a-prime
## 注意事项：
代码在Isprime.ts
回答问题在Question.md
辛苦各位！提前祝国庆快乐！

**Comment by dinoallo** [comment]
我已有权限检视您的仓库，感谢您参加求是潮 2021 秋纳二面，先预祝您面试顺利。

Cheers,
仓管 异特龙
