### ISSUE TITLE
胡锐涛的二面仓库

### ISSUE THREAD

**Issue by yurihuruitao** [QSCTech/2021-fall-round-two#15]
### 胡锐涛的二面提交仓库
链接：https://github.com/yurihuruitao/2021-fall-round-two
### 选做题目：
crazy-jump

### 是否有注意事项，有请说明：
代码放在疯狂跳一跳文件夹下，可以先阅读的 readmd and answers.md ，谢谢！

**Comment by dinoallo** [comment]
我已有权限检视您的仓库，感谢您参加求是潮 2021 秋纳二面，先预祝您面试顺利。

Cheers,
仓管 异特龙
