### ISSUE TITLE
梁思蕴的二面提交仓库

### ISSUE THREAD

**Issue by Ag2SO4pro** [QSCTech/2021-fall-round-two#16]
#梁思蕴的二面提交仓库
*链接https://github.com/Ag2SO4pro/2021-fall-round-two
选做题目：
to-frontend-newbie
#提交答案放在hand-in文件夹中，另外Read_Me.md中附有Reflection环节的回答。

**Comment by dinoallo** [comment]
我已有权限检视您的仓库，感谢您参加求是潮 2021 秋纳二面，先预祝您面试顺利。

Cheers,
仓管 异特龙
