### ISSUE TITLE
王嘉梁的二面提交仓库

### ISSUE THREAD

**Issue by ADSR1042** [QSCTech/2021-fall-round-two#17]
- 链接     https://github.com/ADSR1042/2021-fall-round-two

### 选做题目 ：
1.crazy-jump

### 是否有注意事项，有请说明：
代码放在crazy-jump下的handin文件夹，并请面试官先阅读我新增的 readmd.md ，谢谢！

**Comment by dinoallo** [comment]
我已有权限检视您的仓库，感谢您参加求是潮 2021 秋纳二面，先预祝您面试顺利。

Cheers,
仓管 异特龙
