### ISSUE TITLE
XieJiSS 的二面提交仓库

### ISSUE THREAD

**Issue by XieJiSS** [QSCTech/2021-fall-round-two#2]
## XieJiSS 的二面提交仓库

+ 链接：https://github.com/XieJiSS/2021-fall-round-two

### 选做题目：

1. is-it-a-prime

### 是否有注意事项，有请说明：

代码放在我选做题目的文件夹下的 `prime.ts` 文件

*我的真名在根目录 `README.md` 最开始*（出于隐私考虑不便在公开 issue 中给出，对此带来不便深感抱歉！）

**Comment by palemoons** [comment]
Page not found🤔

**Comment by XieJiSS** [comment]
> Page not found🤔

@palemoons 我按照 commit 文件夹内的要求，邀请了两位出题人和一位仓库维护者

![image](https://user-images.githubusercontent.com/24671280/134330114-5259ca02-0b9a-47d5-afd7-245ea87b9315.png)

![image](https://user-images.githubusercontent.com/24671280/134330453-806a7145-5af3-4703-a31c-52f20da294d5.png)

**Comment by RalXYZ** [comment]
已接受邀请，感谢，祝面试顺利！
