### ISSUE TITLE
xy的二面提交仓库

### ISSUE THREAD

**Issue by IsshikiHugh** [QSCTech/2021-fall-round-two#3]
# **xy**的二面提交仓库

- 链接：https://github.com/IsshikiHugh/2021-fall-round-two/tree/master/commit/qrcode

## 选做题目：

1.qr-code-playground

## 是否有注意事项，有请说明：

检查代码的时候请将编辑器中字符编码改成ANSI，否则可能乱码x
感想我自己另开了一个md文件，放在doc和readme同目录下了

**Comment by dinoallo** [comment]
我已有权限检视您的仓库，感谢您参加求是潮 2021 秋纳二面，先预祝您面试顺利。

Cheers,
仓管 异特龙
