### ISSUE TITLE
biu9的二面提交仓库

### ISSUE THREAD

**Issue by biu9** [QSCTech/2021-fall-round-two#5]
> 链接：https://github.com/biu9/2021-fall-round-two

 **选做题目**
> 1. qr-code-playground`

**注意事项**

> 代码是main.py，姓名&说明写在了README.MD里

**Comment by dinoallo** [comment]
我已有权限检视您的仓库，感谢您参加求是潮 2021 秋纳二面，先预祝您面试顺利。

Cheers,
仓管 异特龙
