### ISSUE TITLE
zjy1298的二面提交

### ISSUE THREAD

**Issue by zjy1298** [QSCTech/2021-fall-round-two#6]
# 2021-fall-round-two
章锦阳的2021求是潮技术 二面提交仓库
***
链接：https://github.com/zjy1298/2021-fall-round-two
***
# 选做题目
1.is-it-a-prime
***
# 代码请看master里的原题目目录内，并且记得查看里面README的第一行我的自我陈述，谢谢。

**Comment by dinoallo** [comment]
我已有权限检视您的仓库，感谢您参加求是潮 2021 秋纳二面，先预祝您面试顺利。

Cheers,
仓管 异特龙
