### ISSUE TITLE
zjr的二面提交仓库

### ISSUE THREAD

**Issue by teeSngRovn** [QSCTech/2021-fall-round-two#8]
# 二面提交仓库

* 链接：[仓库](https://github.com/teeSngRovn/2021-fall-round-two)
# 选做题目
> qr-code-playground
# 注：
> 代码位于`Z_TASK`文件夹子文件夹`qr-code-playground`内，
内附`README.md`回答问题

**Comment by dinoallo** [comment]
我已有权限检视您的仓库，感谢您参加求是潮 2021 秋纳二面，先预祝您面试顺利。

Cheers,
仓管 异特龙
