### ISSUE TITLE
yanyikai的二面仓库

### ISSUE THREAD

**Issue by yanyikai** [QSCTech/2021-fall-round-two#9]
# 2021-fall-round-two

颜弋凯的2021求是潮技术二面提交仓库

链接: https://github.com/yanyikai/2021-fall-round-two

## 选做题目

is-it-a-prime

## 注意事项

先看README.md

**Comment by dinoallo** [comment]
我已有权限检视您的仓库，感谢您参加求是潮 2021 秋纳二面，先预祝您面试顺利。

Cheers,
仓管 异特龙
